language: go

go:
  - "1.11.x"

before_install:  
  - go get github.com/mitchellh/gox

# Below from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - env GO111MODULE=on go build
  - gox -osarch="linux/amd64 windows/amd64 darwin/amd64" -output="pkg/{{.OS}}_{{.Arch}}/{{.OS}}-{{.Arch}}-terraform-provider-twilio" .
  - env GO111MODULE=on go test -v ./...