language: go

go:
  - "1.11.x"

before_install:
  - go get github.com/mitchellh/gox

# Below from https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - env GO111MODULE=on go build
  # rename to match terraform provider conventions:
  #  https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
  - env GO111MODULE=on gox -osarch="linux/amd64 windows/amd64 darwin/amd64" -output="terraform-provider-twilio_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}" .
  - env GO111MODULE=on go test -v ./...

deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: terraform-provider-twilio*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    branch: master
    go: '1.11.x'
