[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
