[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[override]]
  name = "golang.org/x/net"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fatih/structtag"
  version = "1.0.0"
